development:
  adapter: mysql2
  database: big_tv_dev
  username: root
  password:
  pool: 5
  timeout: 5000
  socket: /private/tmp/mysql.sock

test:
  adapter: mysql2
  database: big_tv_test
  username: root
  password: 
  pool: 5
  timeout: 5000
  socket: /private/tmp/mysql.sock

production:
  adapter: mysql2
  host: localhost
  database: big_tv_pro
  username: root
  password: 
  pool: 5
  timeout: 5000
