development:
  adapter: mysql2
  database: big_tv_dev
  username: root
  password: edogawa3
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: big_tv_test
  username: root
  password: edogawa3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  database: big_tv_pro
  username: deploydb
  password: 1+1=deploydb
  pool: 5
  timeout: 5000